# -*- coding: utf-8 -*-
"""64160234_G1_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhE8qIZqWuBU-H9UgEL9jDQZLBIKhrWR

กำหนดให้ 

p แทนประพจน์ 3 มีค่ามากกว่าหรือเท่ากับ 1

q แทนประพจน์ 8 มีค่าไม่เท่ากับ 18

r แทนประพจน์ 20 มีค่าน้อยกว่าหรือเท่ากับ 20

s แทนประพจน์ 25 มีค่าเท่ากับ 2 ยกกำลัง 5

จงเขียนโปรแกรม เพื่อตอบคำถามข้อ 1. - 7. ต่อไปนี้

1.	จงหาค่าความจริงของประพจน์ p $\vee$ $\neg$q

2.	จงหาค่าความจริงของประพจน์ $\neg$(s $\wedge$ r)

3.	จงหาค่าความจริงของประพจน์ (r$\oplus$q) $\rightarrow$ $\neg$s

4.  จงหาค่าความจริงของประพจน์ s$\leftrightarrow$ ($\neg$r $\wedge$ q)

5.	จงหาค่าความจริงของประพจน์ (q$\oplus$$\neg$p) $\vee$ (s$\rightarrow$r)

6.	จงหาค่าความจริงของประพจน์ $\neg$p $\vee$ (p$\oplus$q)  

7.	จงหาค่าความจริงของประพจน์ (r$\rightarrow$s) $\leftrightarrow$ ($\neg$r$\vee$s)

8.  จงสร้างตารางค่าความจริงของประพจน์ $\neg$p $\rightarrow$ (q$\leftrightarrow$r)
9.	จงสร้างตารางค่าความจริงเพื่อตรวจสอบว่า $\neg$($\neg$s $\vee$ r) สมมูลกับ (s $\wedge$ $\neg$r) หรือไม่ 
10. จงสร้างตารางค่าความจริงเพื่อตรวจสอบว่า p$\oplus$($\neg$q $\vee$ s)  เป็นสัจนิรันดร์หรือไม่
"""

!pip install truth-table-generator

# ชื่อ แก้วมณี มารศรี .รหัส 64160234 .กลุ่ม 1 สัปดาห์ที่ 4
p = (3>= 1) 
q = (8 != 18)
r = (20 <= 20)
s = (25 == 2**5)
# 1.	จงหาค่าความจริงของประพจน์ p  or (not q)
print('1. ค่าความจริงของประพจน์ p or (not q) คือ ',p or (not q))

#2. จงหาค่าความจริงของประพจน์  ¬ (s  ∧  r)
print('2. ค่าความจริงของประพจน์ ¬ (s  ∧  r) คือ ',not(s and r))

#3.จงหาค่าความจริงของประพจน์ (r ⊕ q)  →   ¬ s
print('ค่าความจริงของประพจน์ (r ⊕ q)  →   ¬ s คือ',not(r^q) or (not s))

#4. จงหาค่าความจริงของประพจน์ s ↔  ( ¬ r  ∧  q)
print('ค่าความจริงของประพจน์ s ↔  ( ¬ r  ∧  q) คือ ',not(s^(not r and q)))

#5. จงหาค่าความจริงของประพจน์ (q ⊕  ¬ p)  ∨  (s → r)
print('ค่าความจริงของประพจน์ (q ⊕  ¬ p)  ∨  (s → r) คือ ',(q^(not p) or (not s or not r)))

#6. จงหาค่าความจริงของประพจน์  ¬ p  ∨  (p ⊕ q)
print('ค่าความจริงของประพจน์  ¬ p  ∨  (p ⊕ q) คือ ',(not p) or (p ^q))

#7. จงหาค่าความจริงของประพจน์ (r → s)  ↔  ( ¬ r ∨ s)
print('ค่าความจริงของประพจน์ (r → s)  ↔  ( ¬ r ∨ s) คือ ',not(((not p) or (not s))^ (not r or s)))

#8. จงสร้างตารางค่าความจริงของประพจน์  ¬ p  →  (q ↔ r)
import ttg
table_val = ttg.Truths(['p','q','r'],['not p', 'not q xor r','not(not p) or not( not q xor r)'],ints=False)
print(table_val)
table_val.valuation()

#9. จงสร้างตารางค่าความจริงเพื่อตรวจสอบว่า  ¬ ( ¬ s  ∨  r) สมมูลกับ (s  ∧   ¬ r) หรือไม่
import ttg
table_val = ttg.Truths(['s','r'],['not s','not((not s) or r)','s and (not r)','(not((not s) or r))=(s and (not r))'],ints=False)
print(table_val)
table_val.valuation()
print('¬ ( ¬ s  ∨  r) สมมูลกับ (s  ∧   ¬ r)')

#10. จงสร้างตารางค่าความจริงเพื่อตรวจสอบว่า p ⊕ ( ¬ q  ∨  s) เป็นสัจนิรันดร์หรือไม่
table_val = ttg.Truths(['p','q','s'],['not q','not q or s','(not q) or s','p xor (not q) or s'],ints=False)
print(table_val)
table_val.valuation()
print(' p ⊕ ( ¬ q  ∨  s) ไม่เป็นสัจนิรันดร์')